const questions = [
  {
    id: 1,
    description: "question one 1",
    answerOne: "money1",
    answerTwo: "health1",
    answerThree: "fame1",
    answerFour: "religion1",
    correctAnswer: "money1",
    categoryId: 1,
    cote: 10,
  },
  {
    id: 2,
    description: "question one 2",
    answerOne: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk",
    answerTwo: "health2",
    answerThree: "fame2",
    answerFour: "religion2",
    correctAnswer: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk",
    categoryId: 1,
    cote: 10,
  },
  {
    id: 3,
    description: "Question number 3 ?",
    answerOne: "money3",
    answerTwo: "health3",
    answerThree: "fame3",
    answerFour: "religion3",
    correctAnswer: "money3",
    categoryId: 1,
    cote: 10,
  },
  {
    id: 4,
    description: "Question number 4 ?",
    answerOne: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk4",
    answerTwo: "health4",
    answerThree: "fame4",
    answerFour: "religion4",
    correctAnswer: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk4",
    categoryId: 1,
    cote: 10,
  },
  {
    id: 5,
    description: "Question number 5 ?",
    answerOne: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk5",
    answerTwo: "health5",
    answerThree: "fame5",
    answerFour: "religion5",
    correctAnswer: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk5",
    categoryId: 1,
    cote: 10,
  },
  {
    id: 6,
    description: "Question number 6 ?",
    answerOne: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk6",
    answerTwo: "health6",
    answerThree: "fame6",
    answerFour: "religion6",
    correctAnswer: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk6",
    categoryId: 1,
    cote: 10,
  },
  {
    id: 7,
    description: "Question number 7 ?",
    answerOne: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk7",
    answerTwo: "health7",
    answerThree: "fame7",
    answerFour: "religion7",
    correctAnswer: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk7",
    categoryId: 1,
    cote: 10,
  },
  {
    id: 8,
    description: "Question number 8 ?",
    answerOne: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk8",
    answerTwo: "health8",
    answerThree: "fame8",
    answerFour: "religion8",
    correctAnswer: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk8",
    categoryId: 1,
    cote: 10,
  },
  {
    id: 9,
    description: "Question number 9 ?",
    answerOne: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk9",
    answerTwo: "health9",
    answerThree: "fame9",
    answerFour: "religion9",
    correctAnswer: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk9",
    categoryId: 1,
    cote: 10,
  },
  {
    id: 10,
    description: "Question number 10 ?",
    answerOne: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk10",
    answerTwo: "health10",
    answerThree: "fame10",
    answerFour: "religion10",
    correctAnswer: "moneyjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkk10",
    categoryId: 1,
    cote: 10,
  },
];

const difficulties = [
  { id: 1, name: "Easy", coef: 0.4, errorsnumb: 5 },
  { id: 1, name: "Medium", coef: 0.6, errorsnumb: 3 },
  { id: 1, name: "Hard", coef: 1, errorsnumb: 1 },
];

export { difficulties, questions };
